export const DDL = `
CREATE TABLE IF NOT EXISTS Usuario (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL DEFAULT '',
  apellido TEXT NOT NULL DEFAULT '',
  telefono TEXT NOT NULL DEFAULT '',
  tipo TEXT NOT NULL DEFAULT 'indigena'
);

CREATE TABLE IF NOT EXISTS Admin (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  usuario_id INTEGER NOT NULL REFERENCES Usuario(id) ON DELETE CASCADE,
  nivel_acceso TEXT NOT NULL DEFAULT 'basico'
);

CREATE TABLE IF NOT EXISTS Indigena (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  usuario_id INTEGER NOT NULL REFERENCES Usuario(id) ON DELETE CASCADE,
  comunidad_id INTEGER NOT NULL REFERENCES Comunidad(id) ON DELETE CASCADE,
  fecha_nacimiento TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Representante (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  usuario_id INTEGER NOT NULL REFERENCES Usuario(id) ON DELETE CASCADE,
  comunidad_id INTEGER NOT NULL REFERENCES Comunidad(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Comunidad (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL DEFAULT '',
  ubicacion TEXT NOT NULL DEFAULT '',
  descripcion TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Centro_Medico (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL DEFAULT '',
  ubicacion TEXT NOT NULL DEFAULT '',
  contacto TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Noticia (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  usuario_id INTEGER NOT NULL DEFAULT 1 REFERENCES Usuario(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL DEFAULT '',
  descripcion TEXT NOT NULL DEFAULT '',
  categoria TEXT,
  datetime TEXT,
  usuario_nombre TEXT NOT NULL DEFAULT '',
  usuario_apellido TEXT NOT NULL DEFAULT '',
  comunidad_nombre TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Alarma (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  noticia_id INTEGER NOT NULL DEFAULT 1 REFERENCES Noticia(id) ON DELETE CASCADE,
  activa INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Jornada (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  titulo TEXT NOT NULL DEFAULT '',
  descripcion TEXT NOT NULL DEFAULT '',
  fecha TEXT,
  comunidad_id INTEGER REFERENCES Comunidad(id) ON DELETE SET NULL,
  centro_medico_id INTEGER REFERENCES Centro_Medico(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "Noticia_Reaction" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "usuario_id" INTEGER,
  "noticia_id" INTEGER,
  "tipo" TEXT,
  FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("noticia_id") REFERENCES "Noticia" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
`;
